// playlists
export const SELECT_PLAYLIST = 'SELECT_PLAYLIST';
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';

// player
export const CHANGE_PLAY_TIME = 'CHANGE_PLAY_TIME';
export const CHANGE_PLAYING_SONG = 'CHANGE_PLAYING_SONG';
export const CHANGE_SELECT_PLAYLISTS = 'CHANGE_SELECT_PLAYLISTS';
export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING';
